### ISSUE TITLE
Mixer.com/go code not showing in the Unity editor

### ISSUE THREAD

**Issue by chaenator** [mixer/interactive-unity-plugin#100]
I've followed the getting started instructions to get Mixer started but for whatever reason, the code for mixer.com/go is not getting displayed in the Unity editor and I have yet to find any similar issues online.

It's running on Mac OSX High Sierra 10.13.6 with Unity 2018.2.2f1

<img width="1337" alt="screen shot 2018-08-15 at 2 55 03 pm" src="https://user-images.githubusercontent.com/8619137/44167266-bdd49200-a09b-11e8-8c08-d1b852665157.png">

**Comment by payzer** [comment]
If you turn on logging, you can see if there is an error in the logs.

To turn on logging:
1. Go to the menu and select Mixer > Open Mixer Editor.
2. In the Interactive Editor pane expand the advanced tab.
3. Change the Log Level to verbose.
4. Look in the console for error messages.

That will usually point to what is wrong.

**Comment by chaenator** [comment]
So changing it to verbose did not change the outcome in console log but I did get errors that appeared when I opened Unity

I have 2 different errors repeated 2 times

NullReferenceException: Object reference not set to an instance of an object
MixerInteractiveHelper.get__SingletonInstance () (at Assets/MixerInteractive/Source/Scripts/MixerInteractiveHelper.cs:77)
Microsoft.Mixer.InteractivityManager.InitializeInternal () (at Assets/MixerInteractive/Source/Scripts/InteractivityManager.cs:3739)
Microsoft.Mixer.InteractivityManager.get_SingletonInstance () (at Assets/MixerInteractive/Source/Scripts/InteractivityManager.cs:111)
InteractiveSettingsWindow.Initialize () (at Assets/MixerInteractive/Source/Editor/InteractiveSettingsWindow.cs:102)
InteractiveSettingsWindow.OnGUI () (at Assets/MixerInteractive/Source/Editor/InteractiveSettingsWindow.cs:121)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:255)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Aborting
UnityEngine.GUILayoutGroup.GetNext () (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/LayoutGroup.cs:117)
UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUILayoutUtility.cs:309)
UnityEditor.EditorGUILayout.BeginScrollView (Vector2 scrollPosition, Boolean alwaysShowHorizontal, Boolean alwaysShowVertical, UnityEngine.GUIStyle horizontalScrollbar, UnityEngine.GUIStyle verticalScrollbar, UnityEngine.GUIStyle background, UnityEngine.GUILayoutOption[] options) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorGUI.cs:8645)
UnityEditor.EditorGUILayout.BeginScrollView (Vector2 scrollPosition, UnityEngine.GUILayoutOption[] options) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorGUI.cs:8615)
InteractiveSettingsWindow.OnGUI () (at Assets/MixerInteractive/Source/Editor/InteractiveSettingsWindow.cs:124)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:255)

<img width="977" alt="screen shot 2018-08-15 at 3 26 01 pm" src="https://user-images.githubusercontent.com/8619137/44168522-91227980-a09f-11e8-9871-bf1b239eca46.png">

**Comment by AechDub** [comment]
This typically happens with a bad auth token.  Can you create a new auth token and try that?

**Comment by chaenator** [comment]
@AechDub , yup, that was the issue.... its working now! Thanks guys

**Comment by AechDub** [comment]
Excellent. :)
