### ISSUE TITLE
Which versions of Unity3d are supported ? 2018 ?

### ISSUE THREAD

**Issue by rasterknight** [mixer/interactive-unity-plugin#103]
Hi,
Thanks for this SDK.

I did the Getting Started tutorial (first time mixer dev).
When trying to use my latest version of Unity3d: 
2018 2.6f1 LTS :
I could not get the sample to work: it does not show the 6 character code.

I tried with another version from 2017:
2017 4.1f1 LTS
This time it worked, but this 2017 version is quite old .

Is there a list of officialy supported/tested versions ?

Thanks

**Comment by payzer** [comment]
We try to support the latest so if it's not working on 2018 2.6f1, thank you for letting us know. We can look into that.

**Comment by rasterknight** [comment]
Cool thanks. Meanwhile, I will explore with another version from 2018 and let you know asap. Thanks.

**Comment by payzer** [comment]
Sounds good. It might just be that one. I recall someone else was using 2018 and it was okay.

**Comment by AechDub** [comment]
This issue is typically from a problem with the oauth token. Try creating a new token and give that a shot.

**Comment by rasterknight** [comment]
Tested 2018 1.9f2: works.
Tested 2018 2.5f1: works.
So looks like it is latest 2018 2.6f1
Ok will try with a new token now.

**Comment by rasterknight** [comment]
Ok, I recreated a a 2.6 project and it worked with a new OAuth token.
A bit confused on why it did not work the first time around but anyways thanks for the help.

Note1: If I change the OAuth Client ID to garbage in Unity Menu/Mixer/Open Mixer Editor it stills connect and works... is this normal ?

Note2: Anyway in the 2.6 when I add the InteractivityManager prefab in the scene I get some errors/warnings in the console that are not present in previous versions:
In case it might help here they are:  (sorry about image format)
[https://1drv.ms/u/s!AokzVJIKI0KWgc4kFYfqBFy3lDRVdg](url)

**Comment by payzer** [comment]
Thank you for trying out the new versions and I'm glad everything is working now for you. And thank you Aechdub for explaining why in case anyone else encounters the issue. I'll close this issue now. We're glad to hear you got it working!
