### ISSUE TITLE
HandleSceneCreate method

### ISSUE THREAD

**Issue by CahirDev** [mixer/interactive-unity-plugin#104]
Hello,
I found a problem with this method HandleSceneCreate in InteractivityManager class. This method is called after I created scenes from code and inside there is this line:
`_scenes.Add(ReadScene(jsonReader)); `
I think there is a bug here because I think it's only working in situation where we have only 1 scene created. There is a simple "Add" here and name of the function is in single form - "Scene" not "Scenes". But the if is checkng for scenes - thats wierd:
`if (keyValue == WS_MESSAGE_KEY_SCENES)`

The very similar code is in HandleGetScenes, but it calls additional method ReadScenes, so my solution which worked for me was to change this:
`_scenes.Add(ReadScene(jsonReader)); `
to 
`_scenes.AddRange(ReadScenes(jsonReader)); `
so it's using same method now as this HandleGetScenes and it's working fine with this change.

**Comment by AechDub** [comment]
Resolved via PR #105
