### ISSUE TITLE
Groups added to the Beam script on the Beam Manager are "cleared" on play

### ISSUE THREAD

**Issue by staceyhaffner** [mixer/interactive-unity-plugin#11]
Repro Steps:

1. Add BeamManager to scene (empty in this case)
2. Fill in the existing group id with some text.
3. Click **Add** and fill in the new line group id with text.
4. Push **Play**. All groups are cleared out from the UI. If you loop through the list of groups via code they still appear.

**Before:**

![image](https://cloud.githubusercontent.com/assets/4108756/26280469/dd4e9ef2-3d8a-11e7-9b49-047661986a0d.png)

**After:**
![image](https://cloud.githubusercontent.com/assets/4108756/26280480/241acb4e-3d8b-11e7-99ea-ebe386c9804b.png)

**Comment by payzer** [comment]
Great find. Thank you for filing the bug!

**Comment by PetePinelli** [comment]
Oh this is so annoying, especially when you have like 7 groups and decide to add an eighth and have to do it all over again xD

**Comment by payzer** [comment]
Thank you for your patience. We fixed this is the latest release on the releases share. Note: The latest release has changed API names to reflect the new name: Mixer.
