### ISSUE TITLE
DefaultSceneID is ignored unless Groups are setup

### ISSUE THREAD

**Issue by djarcas** [mixer/interactive-unity-plugin#113]
if (helper._groupSceneMapping.Count > 0)
        {
          [SNIP]
            //Possible bug?
            //DefaultSceneID is only applied *if* we have a Group setup - is this by design?
            if (defaultSceneID != string.Empty)
            {
                interactivityManager.SetCurrentScene(defaultSceneID);
                outstandingSetDefaultSceneRequest = defaultSceneID;
            }
        }

Shouldn't the default check and code be outside of the check for having groups? (MixerInteractive.cs ~1229)

**Comment by payzer** [comment]
Yea, looks like a bug. Thanks for letting us know. We'll leave this open so we can track.
