### ISSUE TITLE
Bug in GetParticipantWhoGaveInputForControl

### ISSUE THREAD

**Issue by djarcas** [mixer/interactive-unity-plugin#115]
This happens both in the Buttons demo example and in my own code. The first button press works - successive ones don't. 
```if (MixerInteractive.GetButton("ButtonW"))
        {
            InteractiveParticipant participant = MixerInteractive.GetParticipantWhoGaveInputForControl("ButtonW");
if (participant != null)
                {
                    viewerRecognitionText.text = participant.UserName + " gave you health!";
                    Debug.Log(viewerRecognitionText.text);
                }
                else
                {
                    Debug.Log("Don't know who pressed this?");
                }
}
```

Name gave you health!
Don't know who pressed this?
Don't know who pressed this?
Don't know who pressed this?
Don't know who pressed this?

This doesn't seem to be anything I've done, as it happens in the demo apps. Any thoughts?

**Comment by payzer** [comment]
Thank you for logging this. Based on what you are seeing, it looks like a bug.

**Comment by Garfeild** [comment]
I've faced this issue sometime ago  and fixed in my fork, when I've been playing around with Mixer Interactive integration for game I'm developing. 
Just submitted pull request with changes.

**Comment by payzer** [comment]
Great! It looks like you need to hit the sign button though :)

**Comment by payzer** [comment]
Actually I see you did. Thank you!!

**Comment by Garfeild** [comment]
@payzer thanks for preparing Mixer Interactive SDK for us! :)
