### ISSUE TITLE
No way to detect subscribers or followers?

### ISSUE THREAD

**Issue by djarcas** [mixer/interactive-unity-plugin#119]
Apologies for continually asking questions, but this has me stumped; how can I tell if a participant is following or subscribed to the channel? I can't find any code at all with 'follow' or 'subscribe' anywhere in the Unity integration. 

Can anyone point me in the right direction, or is this simply not supported with the Unity integration?

**Comment by payzer** [comment]
You're right, it's not exposed in the API, but you can hit this endpoint to get it: https://mixer.com/api/v1/channels/12345/relationship?noCount=1&user=12345

**Comment by djarcas** [comment]
You're lovely and brilliant, thank you!
