### ISSUE TITLE
Changing the Default SceneId or Group SceneId to one that doesn't exist causes Beam.OnGoInteractive to not fire

### ISSUE THREAD

**Issue by staceyhaffner** [mixer/interactive-unity-plugin#12]
I know this is a silly one, I found this because I forgot to hit "save" in the Interactive Studio when I renamed my scene. Would be useful to get an error that tells me the SceneId doesn't exist to aid in troubleshooting.

**Repro Steps:**

1. Add an event hook for `Beam.OnGoInteractive`.
2. Add the Beam Manager to a scene (empty in this case).
3. Change either the **Default Scene Id** or **Group Scene Id** to an Id that does not actually exist in the Interactive Studio.
4. The event will never fire.

**Comment by payzer** [comment]
Thank you for pointing this out. A better error would be very helpful!

**Comment by payzer** [comment]
We'll work on a better error. In the meantime or for other cases, if you turn on verbose logging (in the Interactive Editor) and then look for error messages, you'll be able to catch errors like this one.

**Comment by payzer** [comment]
We added a better error message for this error case in the latest release of the SDK.
