### ISSUE TITLE
Unity Mixer Limitations ?

### ISSUE THREAD

**Issue by rasterknight** [mixer/interactive-unity-plugin#120]
Hi, I have yet to check details but does anyone have infos on what are the allowed use case of unity / mixer ?
https://unity3d.com/legal/terms-of-service/software/authorized-streaming

Thanks
Nick

**Comment by payzer** [comment]
It's not exposed in the SDK, but you can hit this endpoint to get it: https://mixer.com/api/v1/channels/12345/relationship?noCount=1&user=12345

**Comment by payzer** [comment]
If you want more info you could email the contact listed.

**Comment by rasterknight** [comment]
Did it, looks like an imbroglio between U and I... nothing much to worry about, yet engines licenses/vs streaming is a subject.. Let's follow the unfolding of it in the coming weeks.
