### ISSUE TITLE
Thread safety issue?

### ISSUE THREAD

**Issue by djarcas** [mixer/interactive-unity-plugin#121]
I'm seeing `ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds System.Array.Copy (System.Array sourceArray, Int32 sourceIndex, System.Array destinationArray, Int32 destinationIndex, Int32 length)` - I'm not entirely sure why, but I'm suspecting someone is writing to the _queuedEvents List whilst the list is being executed - perhaps worth switching to a thread-safe list?

` // Go through all list of queued events and fire events.
            foreach (InteractiveEventArgs interactiveEvent in _queuedEvents.ToArray())
            {`

**Comment by payzer** [comment]
Yes, sorry. Known issue. We've got a backlog item to fix it. Sorry we haven't gotten to it yet. But yes it's a thread safe issue.

**Comment by djarcas** [comment]
It /seems/ to be non-fatal. I'll ignore it for the time being. :)

**Comment by payzer** [comment]
Yea that's why we haven't fixed it yet. It's ignorable, but annoying that it clutters the output.
