### ISSUE TITLE
websocket not open?

### ISSUE THREAD

**Issue by djarcas** [mixer/interactive-unity-plugin#122]
I'm going to *guess* this is due to my mishandling players leaving and rejoining, but that's pure guesswork - is this any sort of known issue, or should I be going over the 'leaving and deleting scenes and groups' code with a fine toothcomb?

1/18/2019 2:25:38 PM|Fatal|WebSocket.<startReceiving>b__179_2:0|WebSocketSharp.WebSocketException: The header of a frame cannot be read from the stream.
                             at WebSocketSharp.WebSocketFrame.processHeader (System.Byte[] header) [0x00000] in <filename unknown>:0 
                             at WebSocketSharp.WebSocketFrame+<>c__DisplayClass73_0.<readHeaderAsync>b__0 (System.Byte[] bytes) [0x00000] in <filename unknown>:0 
                             at WebSocketSharp.Ext+<>c__DisplayClass55_0.<ReadBytesAsync>b__0 (IAsyncResult ar) [0x00000] in <filename unknown>:0 
InvalidOperationException: The current state of the connection is not Open.
  at WebSocketSharp.WebSocket.Send (System.String data) [0x00000] in <filename unknown>:0 
  at Microsoft.Mixer.InteractivityManager.SendJsonString (System.String jsonString) [0x00019] in E:\PGWeb\TwitchPlays\TwitchPlays\Assets\MixerInteractive\Source\Scripts\InteractivityManager.cs:3615 
  at Microsoft.Mixer.InteractivityManager.SendMessage (System.String message) [0x00003] in E:\PGWeb\TwitchPlays\TwitchPlays\Assets\MixerInteractive\Source\Scripts\InteractivityManager.cs:1183

**Comment by payzer** [comment]
No known issues that I know of. I think I've seen that one before. It showed up once, but then I wasn't able to reproduce it since.

**Comment by nsmith1024** [comment]
Hello, so since you are talking about WebSocket, does this mean you are making a version for Unity WebGL? Im making a WebGL game and want to integrate mixer in there,  but mixer dont seem to have a WebGL version for  unity.

**Comment by payzer** [comment]
Thank you for your question. Unfortunately we do not have plans to have a WebGL version of the plugin.

**Comment by nsmith1024** [comment]
Thanks for the response, would it be allowed for me to write my own WebGL mixer player?

**Comment by payzer** [comment]
You definitely can! Although, we usually don't take pull request for new features so it would need to be in it's own repo (kind of like the VR chat implementation). The reason being anything that ends up in this repo we need to maintain so we like to know what we're signing up for :)

**Comment by nsmith1024** [comment]
Yeah! glad to know there is nothing in the mixer terms of service that prevents me from writing my own mixer live stream player for WebGL. 

Basically i just need to get a hold of the steam URL for a particular streamer, can you start me off with the API for that? Thanks

**Comment by payzer** [comment]
Great! Happy coding!

**Comment by nsmith1024** [comment]
So you work for mixer?

**Comment by payzer** [comment]
I do.

**Comment by nsmith1024** [comment]
Do you know which API i can call to get the actual url for the HLS live stream for a particular streamer?

**Comment by payzer** [comment]
I don't. I don't know if there's a specific API since that logic would be handled within the Mixer player most likely.

**Comment by nsmith1024** [comment]
So then its impossible to write a player for it since i cant get the HLS stream to send to the player.

**Comment by payzer** [comment]
I'd say it's more like not supported. Usually people will use an embed if they want video.

Sorry, I misread the thread. I thought you were talking about writing a Unity player for WebGL (player is another word we use for platform support, like we have platform support in this plugin for Win32, Window Store, etc). I didn't realize this was about video playback, not interactivity.

**Comment by nsmith1024** [comment]
So then i cant write a custom player?

**Comment by payzer** [comment]
Unfortunately I'm not on the video side of Mixer. I wouldn't be able to say what the policy is for that. I don't believe we have public APIs for getting the HLS stream though.

**Comment by nsmith1024** [comment]
always bad news, oh well
