### ISSUE TITLE
 BeamManager.SingletonInstance.Participants still seems off

### ISSUE THREAD

**Issue by bzaPetey** [mixer/interactive-unity-plugin#13]
I made sure that I am using the latest version from the releases page.

I am still having some problems with the BeamManager.SingletonInstance.Participants. Here is the code that I am using to test it along with the console output.

I am going through all of the participants and setting them to the crowd group. Then I am going though a list of participants that I have stored in a list to change them over to the player group.

When I am iterating though the BeamManager.SingletonInstance.Participants, it always seems to do the first person 2x and leaves off the last person no mater how many participants there are. The first person is done first and last. So if there are 40 participants, then they are displayed first and then 40th.

```
void CreateTeams()
{
        Debug.Log("Creating Teams");
        Viewers();    //list all of the participants in the channel.
        Players();     //list all of the participants that have clicked the "Play Game" button.

        for (int cnt = 0; cnt < BeamManager.SingletonInstance.Participants.Count; cnt++)
        {
            BeamManager.SingletonInstance.Participants[cnt].Group = crowdGroup;
            Debug.Log("Adding: " + BeamManager.SingletonInstance.Participants[cnt].BeamUserName + " to group: " + BeamManager.SingletonInstance.Participants[cnt].Group.GroupID);
        }

        for (int cnt = 0; cnt < beamPlayers.Count; cnt++)
        {
            beamPlayers[cnt].Group = playerGroup;
            Debug.Log("Adding: " + beamPlayers[cnt].BeamUserName + " to group: " + beamPlayers[cnt].Group.GroupID);
        }
}
```

![console](https://cloud.githubusercontent.com/assets/12932920/26337904/1e1bcff2-3f4a-11e7-88dc-c968b80724f9.gif)

The highlighted line should be adding swishon to the crowdID but for some reason it is doing BurgZergArcade 2x.

**Comment by payzer** [comment]
Thank you for including the code! We'll investigate.

**Comment by payzer** [comment]
We fixed this issue (or at least we hope so, so please let us know if it's still occurring) in the latest release.
