### ISSUE TITLE
Mixer Editor Button "Press Down" event giving an error

### ISSUE THREAD

**Issue by staceyhaffner** [mixer/interactive-unity-plugin#16]
I updated my SDK to the latest. Repro Steps:

1. Go Online, per the usual.
2. Click Mixer -> Open Mixer Editor in the Unity Editor.
3. The Control section is populated with the two controls that currently exist. 
4. Click a control, in this case "startGame" exists on my Default Scene.

Note: If I call the button directly via my own OnClick event tied to a UI element, it works fine.

Stack Trace:

`Error: Error while processing method: giveInput
UnityEngine.Debug:Log(Object)
Microsoft.Mixer.InteractivityManager:Log(String, LoggingLevel) (at H:/GIT/WatchBeam/interactive-sdk-csharp/interactive-sdk-csharp/Source/Microsoft.Mixer.Shared.CSharp/InteractiveManager.cs:3234)
Microsoft.Mixer.InteractivityManager:LogError(String) (at H:/GIT/WatchBeam/interactive-sdk-csharp/interactive-sdk-csharp/Source/Microsoft.Mixer.Shared.CSharp/InteractiveManager.cs:3223)
Microsoft.Mixer.InteractivityManager:ProcessMethod(JsonReader) (at H:/GIT/WatchBeam/interactive-sdk-csharp/interactive-sdk-csharp/Source/Microsoft.Mixer.Shared.CSharp/InteractiveManager.cs:1445)
Microsoft.Mixer.InteractivityManager:ProcessWebSocketMessage(String) (at H:/GIT/WatchBeam/interactive-sdk-csharp/interactive-sdk-csharp/Source/Microsoft.Mixer.Shared.CSharp/InteractiveManager.cs:1377)
Microsoft.Mixer.InteractivityManager:SendMockWebSocketMessage(String) (at H:/GIT/WatchBeam/interactive-sdk-csharp/interactive-sdk-csharp/Source/Microsoft.Mixer.Shared.CSharp/InteractiveManager.cs:1318)
InteractiveSettingsWindow:OnGUI() (at Assets/MixerInteractive/Source/Editor/InteractiveSettingsWindow.cs:268)
UnityEditor.DockArea:OnGUI()`

![image](https://cloud.githubusercontent.com/assets/4108756/26524449/69b52152-42e7-11e7-802c-71d2f88d55b5.png)

**Comment by payzer** [comment]
Thank you for filing the issue. We'll investigate!

**Comment by payzer** [comment]
Thank you for filing this bug. We added an error message for this error in the latest drop of the SDK.
