### ISSUE TITLE
Joystick input throws an error when user reconnects

### ISSUE THREAD

**Issue by TheUnlocked** [mixer/interactive-unity-plugin#17]
Joystick input works fine when the user first loads up interactive. However, if they refresh, any attempt to interact with the joystick will result in an error message (and no joystick event):
```
Error: Error while processing method: giveInput
UnityEngine.Debug:Log(Object)
Microsoft.Mixer.InteractivityManager:Log(String, LoggingLevel) (at H:/GIT/WatchBeam/interactive-sdk-csharp/interactive-sdk-csharp/Source/Microsoft.Mixer.Shared.CSharp/InteractiveManager.cs:3361)
Microsoft.Mixer.InteractivityManager:LogError(String, Int32) (at H:/GIT/WatchBeam/interactive-sdk-csharp/interactive-sdk-csharp/Source/Microsoft.Mixer.Shared.CSharp/InteractiveManager.cs:3350)
Microsoft.Mixer.InteractivityManager:LogError(String) (at H:/GIT/WatchBeam/interactive-sdk-csharp/interactive-sdk-csharp/Source/Microsoft.Mixer.Shared.CSharp/InteractiveManager.cs:3344)
Microsoft.Mixer.InteractivityManager:ProcessMethod(JsonReader) (at H:/GIT/WatchBeam/interactive-sdk-csharp/interactive-sdk-csharp/Source/Microsoft.Mixer.Shared.CSharp/InteractiveManager.cs:1459)
Microsoft.Mixer.InteractivityManager:ProcessWebSocketMessage(String) (at H:/GIT/WatchBeam/interactive-sdk-csharp/interactive-sdk-csharp/Source/Microsoft.Mixer.Shared.CSharp/InteractiveManager.cs:1391)
Microsoft.Mixer.InteractivityManager:OnWebSocketMessage(Object, MessageEventArgs) (at H:/GIT/WatchBeam/interactive-sdk-csharp/interactive-sdk-csharp/Source/Microsoft.Mixer.Shared.CSharp/InteractiveManager.cs:1342)
WebSocketSharp.Ext:Emit(EventHandler`1, Object, MessageEventArgs)
WebSocketSharp.WebSocket:messagec(MessageEventArgs)
WebSocketSharp.WebSocket:message()
WebSocketSharp.<>c__DisplayClass179_0:<startReceiving>b__1(WebSocketFrame)
WebSocketSharp.<>c__DisplayClass83_0:<ReadFrameAsync>b__3(WebSocketFrame)
WebSocketSharp.<>c__DisplayClass77_0:<readPayloadDataAsync>b__0(Byte[])
WebSocketSharp.<>c__DisplayClass55_0:<ReadBytesAsync>b__0(IAsyncResult)
```

Fairly quickly the stack trace goes into DLLs, so I don't know exactly what is going on, but I haven't found any dirty workarounds so this is a somewhat pressing issue.

Another note is that for some reason different results are produced when the Mixer Editor is open. When open, all users have the same joystick (rather than each client having their own like it's supposed to work). I mention this because the joystick error doesn't appear if the editor has been opened at any point while playing, so that may produce a false positive when testing.

**Comment by payzer** [comment]
Thank you for logging the issue we will investigate.

**Comment by payzer** [comment]
Can this be repro'ed on the Joystick example that comes with the plugin? Here's what we tried, but weren't able to reproduce the issue (let me know what step we're missing):
1. Open and run the Joystick sample.
2. Move the capsule through the channel Mixer website.
3. Refresh the browser.
4. Move the joystick again.

**Comment by payzer** [comment]
Actually, I have the repro now. I see you have to close the Mixer Editor. We'll investigate what's going on.

**Comment by payzer** [comment]
Didn't mean to close, meant to comment. We're still investigating.

**Comment by payzer** [comment]
Thank you so much for reporting this issue! We apologize for the frustration. It is fixed in the latest unitypackage in the releases section.

**Comment by TheUnlocked** [comment]
Thank you!
