### ISSUE TITLE
Getting Cost of Buttons Always Returns 0

### ISSUE THREAD

**Issue by PetePinelli** [mixer/interactive-unity-plugin#18]
When using the following code:

`MixerInteractive.Button(e.ControlID).Cost`

I will always get 0, no matter what value I set the Spark Cost to in the Studio.

I know right now pressing buttons with spark cost does not actually take sparks away, I wonder if this might be associated.  If I were to publish my project would this return the correct amount of sparks as well as take them away?

Thanks.

**Comment by payzer** [comment]
Thank you for the question. You are correct, the cost is returning zero because we haven't added spark transactions yet.

**Comment by PetePinelli** [comment]
Awesome thanks for the heads up! Was going to edit put I'll just throw it here:

'e.Participant.ConnectedAt'
will always return 1/1/0001 12:00:00 AM

**Comment by payzer** [comment]
The connectAt one is a bug. Thank you for letting us know.

**Comment by payzer** [comment]
We've added Spark transactions and fixed the ConnectedAt returning the wrong time in the latest release here: https://github.com/mixer/interactive-unity-plugin/issues

Apologies for the delay, the team was out for a couple weeks for E3.
