### ISSUE TITLE
API Implementation Progress

### ISSUE THREAD

**Issue by Mobius5150** [mixer/interactive-unity-plugin#19]
As this SDK is not yet fully feature complete with respect to the Mixer Interactive V2 specification it would be extremely useful to have a document detailing the currently implemented features, such as the one on the [Typescript SDK](https://github.com/mixer/interactive-node/blob/master/TODO.md).

This would be useful in documenting things like dynamic scene creation or participant input disabling not being implemented - so developers don't spend time looking for features that aren't there.

**Comment by payzer** [comment]
Thank you for the feedback. We created a document here:
https://github.com/mixer/interactive-unity-plugin/blob/master/roadmap.md
