### ISSUE TITLE
Set Button Text, Cost, Per-User Cooldown

### ISSUE THREAD

**Issue by PetePinelli** [mixer/interactive-unity-plugin#23]
This is not an issue, rather a request for features if it's possible.

Right now I can only get the information from buttons, but I would like to be able to set the information dynamically as well. Ex:

`MixerInteractive.Button(Button1ID).ButtonText = "Awesome Button";`
Would allow me to change the Button Text from whatever it is to "Awesome Button"

`MixerInteractive.Button(Button1ID).Cost = 500;`
Would allow me to change the spark cost of the button to 500 Sparks.

`MixerInteractive.Button(Button1ID).TriggerCooldown(userID, 5000);`
Would allow me to set a 5 second cooldown on the button for the userID specified.

We are trying to build a simple voting system through interactive because currently the polling system cannot be accessed by users on mobile or xbox. By allowing the streamer to set these values on a client, we can still have a voting system for users on all platforms.

Please let me know if you guys could manage to squeeze this into the development cycle; I know you are all busy but I think these features could be a great addition!

Thanks,
Pete

**Comment by payzer** [comment]
Thank you for letting us know. We will absolutely keep this request in mind as we plan on our roadmap.

Thank you again for the suggestion. I'll leave the issue open until we've got a solution for you :).

**Comment by PetePinelli** [comment]
Awesome thanks a lot payzer!

**Comment by payzer** [comment]
I wanted to share this feature we exposed recently that would enable a voting / polling game:
https://github.com/mixer/interactive-unity-plugin/wiki/Voting-and-polling

Even though I'm closing this issue, we'll keep this scenario in mind and perhaps in the future we can have an event better solution for you!

**Comment by payzer** [comment]
Re-activating since the original issue was not actually fixed. We'll resolve it when there is a way to set button text and spark costs. For cooldowns, they are global, not per participant, but we will take that feedback into consideration!

**Comment by payzer** [comment]
This is fixed in the latest release of the plugin: https://github.com/mixer/interactive-unity-plugin/releases/tag/v0.8.0-beta
