### ISSUE TITLE
Retrieve Button State

### ISSUE THREAD

**Issue by ProbablePrime** [mixer/interactive-unity-plugin#24]
pressed should be true if the button is held down

**Comment by gw1108** [comment]
I can look into a PR for this, but it's a pretty complicated change to fix this issue.

**Comment by payzer** [comment]
@gw1108 thank you for the offer, but yea you probably want to leave that one to the team. It's fairly complicated.

**Comment by hoggy077** [comment]
Just chuck a new event state in that's based on the button events using, when down its set the variable to true and when released change it to false. I just wrote a quick DLL to handle this  and threw it in my projects. Then it's not on the interactive team to add it, it's just a small add-on from you lot

**Comment by payzer** [comment]
Thanks hoggy!
