### ISSUE TITLE
Error accessing list of buttons for stream participant

### ISSUE THREAD

**Issue by EgoAnt** [mixer/interactive-unity-plugin#25]
I'm having an issue with the Unity plugin. I'm trying to access the list of participants and see what the last button they pressed was. When I try to get "foreach (InteractiveParticipant ipc in MixerInteractive.Participants)" I get an error trying to check their buttons.
KeyNotFoundException: The given key was not present in the dictionary.

    string dbg = "";
    if(MixerInteractive.Participants.Count > 0)
	{
		foreach (InteractiveParticipant ipc in MixerInteractive.Participants)
		{
			dbg += ipc.UserName + ":" + ipc.State.ToString();
			if (ipc.Buttons.Count > 0)
			{
				foreach (InteractiveButtonControl b in ipc.Buttons)
				{
					dbg += "[ " + b.ButtonText + ":" + b.ButtonPressed + " ]";
				}
			}
		}
	}

	debugText.text = dbg;

**Comment by payzer** [comment]
Thank you for letting us know. We'll investigate this.

**Comment by payzer** [comment]
Thank you for reporting this bug. The issue is fixed in the latest release: https://github.com/mixer/interactive-unity-plugin/releases/tag/v0.7.8-beta
