### ISSUE TITLE
Unable to Switch Scenes

### ISSUE THREAD

**Issue by runewake2** [mixer/interactive-unity-plugin#26]
Using `InteractivityManager.SingletonInstance.SetCurrentScene("dropbox");` or `MixerInteractive.SetCurrentScene("dropbox");` to set the scene has no effect.

It will change the ID of the current scene listed on Mixer but no observable change happens in the stream. This means that the current Scene ID after this command does become "dropbox" but the actual displayed Scene is always the "default" scene.

After executing the functions above I'd expect the Scene in Mixer Interactive to change, but in Chrome, Vivaldi and Edge that does not happen.

It appears that any changes to the scene will have no effect. The scene does not change when configured in the `MixerInteractive` script either. It is always initialized to the default scene.

**Comment by payzer** [comment]
Thank you for raising this issue. We will investigate.

**Comment by payzer** [comment]
We weren't able to repro, could you try downloading the latest release from this repo? (we very recently fixed a bug that sounds like this issue):
https://github.com/mixer/interactive-unity-plugin/releases 

If that doesn't work, please let us know since it could be something else. Whatever it is, we'll help you get to the bottom of it!

**Comment by runewake2** [comment]
You're right it works with the latest release from this repo. The Asset Store version must be behind. Apologies.

**Comment by payzer** [comment]
No worries, we're glad you got your issue solved. And yes as you noticed, the Asset Store version is usually a week or so behind the GitHub version because the publishing process to the Asset Store takes some time.
