### ISSUE TITLE
Doesn't run on MAC

### ISSUE THREAD

**Issue by payzer** [mixer/interactive-unity-plugin#30]
This is a coming platform feature, but currently the SDK doesn't not run on MAC. We will look to fix this in the future. For now, disable Mixer for your MAC build.

**Comment by samdes-ms** [comment]
Would love running Unity + Mixer Plugin on mac, thanks guys!

**Comment by payzer** [comment]
Thank you for +1'ing the suggestion!

**Comment by stuarttempleton** [comment]
+1 here, too! I would also appreciate having this available for our mac builds (and Linux)!

**Comment by AechDub** [comment]
Resolved issue.
