### ISSUE TITLE
Allow channel scopes

### ISSUE THREAD

**Issue by payzer** [mixer/interactive-unity-plugin#31]
A few developer have asked to be able to use the SDK to make channel queries. In the interim, it would be useful to expose a way to get the channel scopes and token so they can make channel queries.

This issue will track adding that to the SDK.

**Comment by ProbablePrime** [comment]
As a suggestion, the json file for a project could be expanded to contain a string with the scopes they'd like to request.

scopes are space delimited strings.

e.g. "interactive:robot:self channel:details:self"

**Comment by payzer** [comment]
An excellent idea! Thank you for that.
