### ISSUE TITLE
Errors building for UWP with Mixer and Xbox Live (Unity 5.6)

### ISSUE THREAD

**Issue by dammittom** [mixer/interactive-unity-plugin#33]
We have Mixer setup and working when we run the game through the editor. This is with Unity 5.6.3p3.

When we try to build a package with the "Windows Store" set as the current platform, we get this error:
Assets\MixerInteractive\Source\Scripts\MixerInteractive.cs(624,9): error CS0012: The type 'Dictionary<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

For UWP / Windows Store, we have the following settings:
- Scripting backend: IL2CPP
- Api compatibility level: .NET 4.6
- SDK: Windows 10
- Target device: any device
- UWP Build type: D3D

(Changing the scripting backend gives us different errors than this, but we need to have it set to IL2CPP and .NET 4.6 in order to add Xbox Live support, as documented here: https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-partner/partner-unity-uwp-il2cpp)

**Comment by hoggy077** [comment]
It's been a while so pardon if I'm rusty with my errors, but you should be able to reference everything you need for it. I haven't played with  IL2CPP so I'm not aware if it counteracts this, but in your script can't you do using system.collections?

**Comment by dammittom** [comment]
This error is coming up from the MixerInteractive.cs script. It already has the correct usings, as far i can tell.

`using System.Collections.Generic;
using System.ComponentModel;
using System.Net;
using System.Net.Security;
using UnityEngine;
using Microsoft.Mixer;
using UnityEngine.Networking;
using System.Collections;
#if UNITY_WSA && !UNITY_EDITOR
using Windows.UI.Core;
using Windows.ApplicationModel.Core;
using System;
using Windows.Security.Credentials;
using Windows.Security.Authentication.Web.Core;
using System.Threading.Tasks;
#endif
#if UNITY_XBOXONE && !UNITY_EDITOR
using System;
using System.Runtime.InteropServices;
using System.Text;
using System.IO;
using System.Collections;
#endif
`

**Comment by hoggy077** [comment]
Have you tried shoving "system.collections." Infront of it, I know it sounds stupid but no harm in trying to call the full function I guess. After that I'm out, I see the error and I get the error but if that don't fix it then im out of ideas

**Comment by hoggy077** [comment]
i feel a tiny bit like an idiot right now, but, isn't dictionary<> a call from system.collections.generic? https://msdn.microsoft.com/en-us/library/system.collections.generic(v=vs.110).aspx yes it is... i need a facepalm image attached here.

**Comment by dammittom** [comment]
A couple of options seem to be available for this:

- Update to Unity 2017.1, where we were told the issue isn't happening. 
- Wrap the SendInteractiveMessage() function in a UNITY_XBOXONE macro. We're not using the function in our Mixer interactive implementation, so we're okay disabling it from the build. (I didn't think of this sooner since it was early in our Mixer development and I wasn't sure yet what API calls we would need).

**Comment by TimeWarDoctor** [comment]
I'm running Unity 2017.3.b02, and I have a similar issue where the plugin won't run in the UWP application I built out of Unity3D.

**Comment by payzer** [comment]
@dammittom you probably don't need that function so wrapping it is fine. @TimeWarDoctor thank you for letting us know.

**Comment by TimeWarDoctor** [comment]
@payzer where may I find the source code to the DLL Microsoft.Mixer.Uwp.CSharp?  I'd like to try something out.

**Comment by payzer** [comment]
@TimeWarDoctor it's in the latest release: https://github.com/mixer/interactive-unity-plugin/releases

If you go to: Assets\MixerInteractive\Source\Shared

**Comment by TimeWarDoctor** [comment]
Thank you Sir.

**Comment by payzer** [comment]
Unfortunately, this may be a Unity IL2CPP issue. We did end up changing the plugin to be almost 100% C# source though which would hopefully make diagnosing this type of issue easier in the future. We'll close this issue unfortunately because there's not much we can do about it after investigating. Please let us know though if it is blocking you and we can work 1:1 with you to find a solution.
