### ISSUE TITLE
Mulitple Unity scenes causes the game to not recieve button press imputs from mixer.com. 

### ISSUE THREAD

**Issue by Dklein2** [mixer/interactive-unity-plugin#37]
Hi, 

I currently have my game set up with these scenes in unity 'Main Menu' > 'World 1' when I run the game, it does not receive button presses from the participants that are interacting with the stream.

Setting the game up to only use my 'world 1' scene fixes this issue. 

I am not seeing any relevant code errors on the mixer end or my games end.

**Comment by payzer** [comment]
Thank you for posting. We can help you troubleshoot this issue if you let us know some more information. Do you have multiple groups?

What might be happening is that in order for a viewer to see a different scene (one that's not the default scene), you'll need to put them in a group and then set the group to the particular scene.

**Comment by payzer** [comment]
This has been open for a while. We'll go ahead and close it now. If it still repros and you can get us additional information we can help troubleshoot the issue.
