### ISSUE TITLE
Access to viewer avatars

### ISSUE THREAD

**Issue by EgoAnt** [mixer/interactive-unity-plugin#38]
It would be great if when a Participant joined we had access to their avatar.

**Comment by connor4312** [comment]
You can grab the URL from the user ID. For instance, I'm use ID 146, I can get a 64x64 image of myself at this URL:

```
https://mixer.com/api/v1/users/146/avatar?w=64&h=64
```

![](https://mixer.com/api/v1/users/146/avatar?w=64&h=64)

**Comment by EgoAnt** [comment]
Thank you, this is working now.
