### ISSUE TITLE
GoInteractive does not seem tot work

### ISSUE THREAD

**Issue by FireFlyForLife** [mixer/interactive-unity-plugin#39]
When I try the examples, I get the initial popup to go to mixer.com/go and fill in the code, I then give permission and restart the unity editor. However, then nothing happens, it just sits there without an error or anything in the log and on the channel I can see the stream being live but no buttons are underneath.

I have tried creating a new project in the mixer studio, and copying the new ID to the mixer config, but that did not work.

Any help or pointers to a potential problem would be highly appreciated.

**Comment by payzer** [comment]
The easiest way to figure out what is happening is to:
1. Press play in Unity.
2. Open the Mixer Editor (you can get to the Mixer Editor by going to the Mixer menu and selecting Mixer Editor).
3. Expand the Advanced section.
4. In the logging dropdown, set it to verbose.
5. Make sure the Unity console window is open and all debug messages are unfiltered.
6. Run your code and see what the console prints out.

From there you might find what the error is, but if not, you can post the message here and we can help you troubleshoot further. If there is no console output, then let us know and we can help.

Here's additional documentation with the most common issues:
https://github.com/mixer/interactive-unity-plugin/wiki/Troubleshooting-guide

**Comment by FireFlyForLife** [comment]
I tried that however I noticed that my setting always resets after I press play (#40 ). So when I try it normally my console is empty.
I also tried doing a launch with the "Play and go Interactive" button on the mixer editor, then changing the setting to verbose and pressing "Go Interactive" but that only gave me the following output: 
![image](https://user-images.githubusercontent.com/14093640/36344697-8c2f4d58-141e-11e8-8842-0ef358d84bdb.png)

**Comment by payzer** [comment]
Thank you for sharing the screenshot. That output means that you have successfully connected to Mixer and got the participantJoin message. So it does appear as though you are connecting.

For the buttons not appearing on the website. Does your scene in interactive studio have buttons for each of the layout types? (desktop, tablet, mobile)

**Comment by FireFlyForLife** [comment]
It did have previously, I just added them all for the current test project and it still doesn't show buttons.

**Comment by payzer** [comment]
My output also lists all the controls in my scene. Since it looks like from the above output, you are able to connect, it would be useful to see the controls in the scene so we could see if the button is there.

**Comment by FireFlyForLife** [comment]
Yes, Today I even deleted the whole MixerInteractive folder and reimported it from the Asset Store. The 2 lines of output I received are from when I changed the verbosity level and then pressed "Go Interactive" in the mixer editor. I do not get any output when I try to pause then play in the editor at first and then change the verbosity and then unpause, the console stays empty.

**Comment by FireFlyForLife** [comment]
Or is the asset store version not the latest release on github?

**Comment by payzer** [comment]
Sorry for this not working. I actually did the same exact thing (downloaded from the asset store and ran the default sample) and everything worked as expected with 10 lines of debug output.

The asset store version isn't the same one as github. They are close though and often identical (the asset store is sometimes behind by a few days).

**Comment by payzer** [comment]
Oh.... wait. I think I might know what happened.

**Comment by payzer** [comment]
Don't press the Go Interactive button in the editor, we'll need to remove that since it's causing confusion. What you'll want to do is run the "Basic" example. Press the "Go interactive" button in the Unity scene. Then it will probably work.

The go interactive button in the editor simulates going interactive, but doesn't actually connect to the Mixer service.

I'll use this issue to track removing that button to avoid future confusion.

**Comment by FireFlyForLife** [comment]
I tried the pause->play->log level set to verbose->unpause-> clicking on the in game Canvas "Go Interactive" but that still shows nothing in the console I am afraid.

**Comment by Brentenbrood** [comment]
I'm having the same trouble. The Go Interactive button in the scene of the basic scene does nothing.

Just a quick note; change line 102 InteractiveSettingsWindow.cs to;
`string loggingLevel = EditorPrefs.GetString("Mixer_LoggingLevel");`

**Comment by payzer** [comment]
When you say it does nothing, something would at least show up in the console log? Or is there literally nothing in the console log?

**Comment by FireFlyForLife** [comment]
it's literally an empty console.

**Comment by FireFlyForLife** [comment]
I will try to restart but now set it up on my laptop, lets see if that makes a difference

**Comment by payzer** [comment]
That's really strange. I've never seen that before (and we've done troubleshooting on a lot of connection issues).

**Comment by FireFlyForLife** [comment]
Hmm alright so when I tried it on my laptop everything went fine... I am now trying to see if it works on my pc if I connect it to my newest mixer test project

**Comment by Brentenbrood** [comment]
I tried running it on another computer, no luck again.
When I logged the exception in OnWebSocketClose in InteractivityManager I got error code:
`4020 The interactive version is not found, or you do not have access to it.`

**Comment by payzer** [comment]
Thank you for letting us know. I'm glad both got it working. I'll close the issue now.

**Comment by connor4312** [comment]
It makes sense that editors, as they're able to modify the project, should be able to connect with it too. We'll track this internally and put a fix in for it this coming week. Thanks for opening an issue, and your patience debugging!

**Comment by connor4312** [comment]
This change is now in production.
