### ISSUE TITLE
"Log Level" setting resets on play

### ISSUE THREAD

**Issue by FireFlyForLife** [mixer/interactive-unity-plugin#40]
In the Mixer editor under advanced you can select the Log Level. By default this is on minimal, however you can change it to verbose (which is useful when I don't know why my buttons are not appearing). However when you launch the editor, that setting gets reset to minimal and I can't see if my authentication etc. is working.

**Comment by payzer** [comment]
Thank you for opening this issue. It's a known issue which we need to fix. If GoInteractive is called on play, which is the case for the examples, you can press the pause button before pressing play. This will allow you to change the log level when in play mode.

I tried the example just now and there may be a service issue.

**Comment by payzer** [comment]
FYI - I just tried the button sample myself and the giveHealth button appeared so it's not a service issue.

**Comment by FireFlyForLife** [comment]
like @brentenbrood said in #39 , the issue is because the EditorPrefs are not setting and getting from the same string, at InteractiveSettingsWindow line 102 it gets from "Interactive_LoggingLevel" and on line 461 it sets to "Mixer_LoggingLevel"

**Comment by payzer** [comment]
This is now fixed in the latest release. Thank you for the PR.
