### ISSUE TITLE
[Xbox One] MixerEraNativePlugin_GetXToken always retrieving token for first user signed in.

### ISSUE THREAD

**Issue by szymon112233** [mixer/interactive-unity-plugin#58]
After switching active profile in game with previous user still signed in, MixerEraNativePlugin_GetXToken is retrieving a token for the previous user and not the current one. As an effect, despite the fact that active user changed,  the previous one goes interactive.

Could you please enable an option to pass an user parameter for the function or tell us the service url so we could call GetTokenAndSignatureAsync ourselves and get the right token.

**Comment by payzer** [comment]
Thank you for raising this issue, we will investigate a way to either take the current user or expose a way to do so.

**Comment by payzer** [comment]
No ETA yet, but if you are prepping for cert, do you have a developer account manager who can put you in contact with us? If not, you can reach out to mixerdeveloperinfo@microsoft.com. 

We could do something short term to unblock you.

**Comment by payzer** [comment]
To close the loop. We have added an API that will enable folks to get the correct user on Xbox One. It's usage is documented here in the section called "Handling multiple users":
https://github.com/mixer/interactive-unity-plugin/wiki/Mixer-and-Xbox-One
