### ISSUE TITLE
InteractivityManager.ReadControls doesn't handle null (version 1.0)

### ISSUE THREAD

**Issue by rwared11** [mixer/interactive-unity-plugin#60]
We have 11 scenes setup in the Mixer builder, but I found that only a random subset of these were being found when I queried MixerInteractive.GetScene.

In the end I found that the list of scenes seemed to be received in a random order, and one of them had a null control group which caused parsing to malfunction at that point, sometimes it would resynchronise and read some more scenes, sometimes not.

In ReadControls, I changed the while loop to the following, and it seemed to then always parse all 11 scenes correctly.

                while (jsonReader.Read() && jsonReader.TokenType != JsonToken.Null && jsonReader.TokenType != JsonToken.EndArray)

**Comment by payzer** [comment]
Thank you for letting us know! Much of the team is currently at GDC, but we'll look to integrate this when we're back.
