### ISSUE TITLE
participantID in InteractiveControl.cs

### ISSUE THREAD

**Issue by gw1108** [mixer/interactive-unity-plugin#61]
I thought this would do something, but right now I don't think anything references this. Is it planned in the future to do something? I need to get the particpantID of whoever pressed a button.

**Comment by gw1108** [comment]
Turns out you need to have MixerInteractive.GetParticipantWhoGaveInputForControl to get who pressed what button. Also, make sure the script execution order has MixerInteractive executed before DefaultTime. Or call DoWork().

**Comment by payzer** [comment]
Glad you figured it out. We'll try to make this clearer in our documentation. And thank you for posting the solution! That way others who come across the same issue will be able to reference this.

**Comment by gw1108** [comment]
I still don't know what participantID in InteractiveControl.cs does though?

**Comment by payzer** [comment]
I'll check on that now & reply shortly

**Comment by payzer** [comment]
It's not public, it's marked internal "internal int participantID;" so don't worry about it :) If you're curious it's used for internal tracking that some of the public APIs use.
