### ISSUE TITLE
Missing flag reset

### ISSUE THREAD

**Issue by avi90** [mixer/interactive-unity-plugin#63]
Hi, while browsing your code I stumbled upon this bool flag which never gets reset and thus causes disk writes on every frame. Thought I'd bring this to your attention.
https://github.com/mixer/interactive-unity-plugin/blob/37b25aaa42f0171622ce80701828fe362247dd8b/Source/InteractiveSDK/Assets/MixerInteractive/Source/Scripts/MixerInteractiveHelper.cs#L322

**Comment by payzer** [comment]
Thanks for bringing this to our attention. We will definitely fix it.

**Comment by payzer** [comment]
We fixed this in our latest release. Thank you again for bringing the issue to our attention, we appreciate it!
