### ISSUE TITLE
Getting started documentation isn't clear at all.

### ISSUE THREAD

**Issue by Foxxite** [mixer/interactive-unity-plugin#69]
Meant to get you started, well the documentation doesn't help at all. Unclear directions and stuff mentioned that doesn't even exist. please update.

**Comment by payzer** [comment]
Thank you for the feedback. We will review the documentation and make sure it is accurate. Any chance you could give more specific feedback on what was unclear for you?

**Comment by payzer** [comment]
Reviewed the getting started docs and went through the steps. Everything was working. Could you provide more specifics about what didn't work so we can improve?

I'll leave the issue open for another day so you can help us out with the places where the documentation was confusing for you.

**Comment by payzer** [comment]
I'm going to close this issue for now (without specifics it's hard for the team to take action to fix it). Feel free to file a new issue or re-open this one with specific things you'd like to see improved or changed. Thank you again for downloading the SDK and taking the time to file the issue though.

**Comment by kurodansei** [comment]
I have a specific problem with using the Get-Started Documentation. 
On the step "Link Your Game to The Mixer Service" 
I can find the Version ID but I can't find the place to put it designated by the instruction.
Open the **Mixer** menu and select **Open Mixer Editor**.

Basically the biggest issue I'm having is that there is little to no explanation to where and what each menu item is. I lucked into some of the steps up to that point, but I'm having real problems figuring out where that **Open Mixer Editor** button is. 

I would suggest more screenshots or more links to the things you have bolded that you want us to click on so we can't miss them.

**Comment by payzer** [comment]
Thank you! This is very useful feedback!! I re-opened the issue and we will get that fixed!

**Comment by AechDub** [comment]
Docs updated with more screenshots.
