### ISSUE TITLE
Mixer Log Level Doesn't Do Anything

### ISSUE THREAD

**Issue by gw1108** [mixer/interactive-unity-plugin#71]
https://github.com/mixer/interactive-unity-plugin/blob/bcbe20276a4feb0fbabe5fc1e7b312ae0f34c5af/Source/InteractiveSDK/Assets/MixerInteractive/Source/Scripts/InteractivityManager.cs#L3553

To fix this InteractivityManager.cs needs to set `LoggingLevel = (LoggingLevel)Enum.Parse(typeof(LoggingLevel), EditorPrefs.GetString("MixerInteractive_LoggingLevel"));`

**Comment by payzer** [comment]
Thank you for pointing this out. We'll get this fixed.

**Comment by payzer** [comment]
Thank you so much for taking the time to log the issue, but actually this particular piece of code doesn't really get used so it doesn't affect the logging level. Here's a bit how the loglevel works:
1. If the editor pane has a value set that always takes precedence.
2. If you problematically set it, then that it next.

The code above just sets some defaults and then those default will get overridden (if you've toggled the log level in the editor UI)

**Comment by gw1108** [comment]
Just checked to see if Mixer->OpenMixerEditor->Log Level UI did anything on Unity 2017.3.1f1. After hitting Play in Assets/MixerInteractive/Examples/Basic.unity scene Line 3553 from InteractivityManager.cs is called starting from MixerInteractive.cs Line 116. 

Steps:
1. Go to Mixer->OpenMixerEditor->Log Level to Verbose.
2. Open scene Basic
3. Hit play.
4. Click the Mixer Interactivity Toggle.
5. Notice there are not any Debug.Log messages in the UnityEditor.

Expected Result:
Expected Debug.Log messages to fill the Unity console.

**Comment by payzer** [comment]
Thank you for the steps. We'll re-open the issue and continue looking. Sorry for closing too early and thank you for being persistent.

**Comment by AechDub** [comment]
This should be resolved with the latest release.
