### ISSUE TITLE
Joystick X and Y values not reset on mouse up when mouse is moving.

### ISSUE THREAD

**Issue by robjonescoatsink** [mixer/interactive-unity-plugin#74]
If the user is also moving the mouse when they release the stick then the X and Y values of the joystick remain at their last value. 

I would expect this to behave in the same way as releasing the stick when the mouse is not moving, resetting to zero on mouse up.

**Comment by payzer** [comment]
Thank you for letting us know. We'll look into this issue.

**Comment by AechDub** [comment]
This is a server side issue.  We should have the fix out soon and you won't need to take an update for it.  I'll confirm once the fix is deployed.

**Comment by AechDub** [comment]
The fix for this has been deployed.  Please let us know if you encounter further issues.

**Comment by robjonescoatsink** [comment]
Excellent Thanks
