### ISSUE TITLE
[System.Serializable]

### ISSUE THREAD

**Issue by bzaPetey** [mixer/interactive-unity-plugin#8]
Could we get the [System.Serializable] added to the BeamParticipant and BeamGroup. This is used in the Unity inspector when serializing datatypes. Let me know if you need more information in this.

**Comment by payzer** [comment]
Great suggestion. We'll look into it.

**Comment by payzer** [comment]
We added the attribute to these two classes in the latest release, but it's probably not quite there yet (the properties of the classes don't show in the inspector). 

We're working through some other changes and will plan to fix this issue along with the other changes. We're currently targeting late next week for that.

**Comment by bzaPetey** [comment]
Unity does not serialize the properties. The only ways that i can think of to get by this is to use a private var and then use set and get on them. The second way is to create a custom inspector for it, The later option is a little more work, but does not require any touching of the functional code.

**Comment by payzer** [comment]
Thank you for that information. In that case, we might have done what you need? We added [System.Serializable] to the classes.

**Comment by bzaPetey** [comment]
Turns out that it has to be a monobehaviour to build a custom editor. Makes sense since it has to be a component that can be placed on a GameObject.

**Comment by payzer** [comment]
Unfortunately those classes won't be able to inherit from monobehavior since we're trying to keep the core of the SDK usable for other C# based engines & C# in general. Should I close the issue or is there more we can do?

**Comment by bzaPetey** [comment]
Is it possible to use the [SerializeField] tag with private variables with public accessors? If not that is ok as I do not need that level of information in the inspector for the few current projects that I have planned for Beam.
I am currently just inheriting and adding what i need that way, but would be nice if I could get it built in already.

**Comment by payzer** [comment]
That's a great suggestion. We'll look into it.
