### ISSUE TITLE
Bluescreen not showing up the 6\d code

### ISSUE THREAD

**Issue by Gwalbert** [mixer/interactive-unity-plugin#80]
Hi, 

The 6 digit code that has to show at mixer bluescreen : "enter this code at http://mixer.com/go" is not showing me up. Is there any limitation (ex geographical) for this testing host?
I fallow by this toutorial and I havent got any errors.
https://channel9.msdn.com/Shows/dotGAME/Getting-started-with-Mixer-Interactivity

![screen](https://user-images.githubusercontent.com/10687484/40257254-c81af720-5aed-11e8-8d89-327b4c08a1e6.png)

**Comment by AechDub** [comment]
Could you provide a fiddler trace?

**Comment by payzer** [comment]
Or if it's easier for you turn on verbose logging. You can change the log level in the Mixer Editor pane.

**Comment by Gwalbert** [comment]
@payzer : i try nothing change. code is "invisible".

fiddler trace show:
![Uploading fiddler.png…]()

**Comment by Gwalbert** [comment]
hmm ... I have the newest Unity v 2018.1.0f2. 
... i'm for sure logged in to mixer ...

**Comment by AechDub** [comment]
Did you add your oauth and version id in the Mixer editor?

**Comment by Gwalbert** [comment]
off course: OAuth Client ID (long alphanumeric) and Version ID (6 digits) and saved project inform.

**Comment by AechDub** [comment]
https://github.com/mixer/interactive-unity-plugin/blob/master/Source/InteractiveSDK/Assets/MixerInteractive/Source/Scripts/InteractivityManager.cs#L575

Trying debugging here.  You should have a proper AppID and exchangeCode.  If not, it will fail.

**Comment by Gwalbert** [comment]
I dotn't think so at 14:35: he says "we can use enyone" (but I try. and nothing) i also check http://mixer.com or http**s**://mixer.com.

**Comment by Gwalbert** [comment]
One new thing i suspect when i write code in VisialStudio i haven't got autocomplete the Mixer.Interactive methods so mayby i need to .manualy, include mixer library. But Including "using Microsoft.Mixer;" dosn't work for me.

**Comment by payzer** [comment]
The lack of autocomplete might be a Unity issue. Unity is getting better about it, but still often puts code in the "misc files" category so you need to manually include them for intellisense. But if you don't get compile errors when doing using Microsoft.Mixer, then that's a sign it's working fine.

**Comment by AechDub** [comment]
@Gwalbert this looks to be something with your oauth token.  If you try creating a new one, it should fix your issue.

I'm going to close this ticket.  If you're still experiencing issues, please re-open.
