### ISSUE TITLE
Can't obtain OAuth token

### ISSUE THREAD

**Issue by gordonklarson** [mixer/interactive-unity-plugin#88]
I've been trying to run the example code included with the plugin. Nothing happens after checking the checkbox when running the scene. All I get is the following output from the server every few seconds: 

Trying to obtain a new OAuth token. This is an expected and repeated call.
InteractivityManager._Log()    Assets/MixerInteractive/Source/Scripts/InteractivityManager.cs:3789
3787:           return;
3788:       }
-->3789:       UnityEngine.Debug.Log(message);
3790:   }

InteractivityManager.TryGetTokenAsync()    Assets/MixerInteractive/Source/Scripts/InteractivityManager.cs:501
499:   private void TryGetTokenAsync()
500:   {
-->501:       _Log("Trying to obtain a new OAuth token. This is an expected and repeated call.");
503:       mixerInteractiveHelper.OnInternalWebRequestStateChanged -= OnRequestOAuthExchangeTokenCompleted;

InteractivityManager.OnInternalCheckAuthStatusTimerCallback()    Assets/MixerInteractive/Source/Scripts/InteractivityManager.cs:496
494:   private void OnInternalCheckAuthStatusTimerCallback(object sender, MixerInteractiveHelper.InternalTimerCallbackEventArgs e)
495:   {
-->496:       TryGetTokenAsync();
497:   }

MixerInteractiveHelper.CheckAuthStatusBackgroundWorkerDoWork()    Assets/MixerInteractive/Source/Scripts/MixerInteractiveHelper.cs:450
448:       if (OnInternalCheckAuthStatusTimerCallback != null)
449:       {
-->450:           OnInternalCheckAuthStatusTimerCallback(this, new InternalTimerCallbackEventArgs());
451:       }
452:   }

_ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by payzer** [comment]
This means that:
1. The SDK has retrieved a short code and is displaying it to the user
2. It is waiting for you to go to mixer.com/go and log in

After that it will obtain the OAuth token and continue.

Let us know if that fixes your issue?

**Comment by gordonklarson** [comment]
No code is being displayed. All I see is "Enter this code at http://mixer.com/go" and nothing else. I've also checked the AuthCode object in the scene and the Text component is set to the empty string.

**Comment by payzer** [comment]
Thank you, that means it must have failed to display the shortcode in the Unity UI (is the UI element hidden?). But it probably got one successfully otherwise it wouldn't get that far. It would have printed to debug output that it failed to retrieve a short code.

**Comment by gordonklarson** [comment]
I managed to get it to work finally. Created a new OAuth client in the mixer developer lab and it seemed to fix the issue. It's strange because all the settings are the same except for the client name.
