### ISSUE TITLE
Unity Mixer Plugin import, then compile error with WebSocketSharp

### ISSUE THREAD

**Issue by creativedrewy** [mixer/interactive-unity-plugin#91]
Hey team, I just imported the Mixer SDK from the Unity Asset store today. Right after I imported I attempted to build my project I got this error:

```
Assets/MixerInteractive/Source/Scripts/InteractivityManager.cs(943,54): 
error CS0246: 
The type or namespace name `WebSocketSharp' could not be found. Are you missing an assembly reference?
```

This occurs in a few files; it would appear the WebSocketSharp dependency is missing from the SDK.

I found the WebSocketSharp repo here on GitHub; is this something we need to build ourselves to run the SDK? Is there some dependency-downloading step that I'm missing?

**Comment by creativedrewy** [comment]
Update: This appears to the place where the dependency issue starts:

[https://github.com/mixer/interactive-unity-plugin/blob/master/Source/InteractiveSDK/Assets/MixerInteractive/Source/Scripts/InteractivityManager.cs#L51](https://github.com/mixer/interactive-unity-plugin/blob/master/Source/InteractiveSDK/Assets/MixerInteractive/Source/Scripts/InteractivityManager.cs#L51)

**Comment by payzer** [comment]
What platform were you building for? Or was this the editor?

**Comment by creativedrewy** [comment]
Sorry for the lack of details! I'm building a project on Unity Mac. Attempting to run what was a previously running game inside the editor displays the compiler.

Also would try to compile within Visual Studio Community on Mac. Same compiler error.

**Comment by payzer** [comment]
Ah okay. Our MAC SDK developer is on vacation this week so I'll try my best to figure this out.

Based on what I see in the version on GitHub, looks like if you:
1. Go into Assets\MixerInteractive\Source\DLLs\Win32\websocket-sharp.dll
2. In the Inspector, check the checkbox for Mac OS X then it'll probably fix the issue.

**Comment by creativedrewy** [comment]
A small update: I tried the above suggestion, but unfortunately the exact same compilation error occurred. It's almost like it had no effect on Unity, though it did update the .meta file for the dll.

I actually tried manually adding references to the .dll into both of the project .csproj files similar to how other .dll files are referenced and that enabled me to successfully build the project within Visual Studio Mac. Of course, this wasn't the actual solution as it appears Unity auto-generates the .csproj files each time you open the project, and upon auto-gen any references to the websharp .dll were gone. Very strange.

**Comment by payzer** [comment]
Yea Unity's use of the .csproj isn't like normal.

**Comment by creativedrewy** [comment]
Any updates? Thanks!

**Comment by payzer** [comment]
We're going to look at it. In the meantime, this is a workaround:

https://gist.github.com/bargle/4ac1c2f65d201f1734c04177b6b5d3fe

**Comment by creativedrewy** [comment]
Unfortunately that gist is fixing something related to thread-safety. Alas, the WebSocketSharp compile error is still present.

**Comment by payzer** [comment]
Ah, sorry wrong issue :)

**Comment by payzer** [comment]
Not yet. The dev was looking at something else today. I'll let him know.

**Comment by CaliCastle** [comment]
Any update on how to fix this issue? I'm getting the same compilation error here

**Comment by gadenton** [comment]
@creativedrewy if you're still having this problem what I did to fix it was not just check the checkbox enabling the dll for Mac OSX, but then I also had to change a dropdown from Windows to "Any OS".
That dropdown was on the Editor Settings tab of platform settings.
