### ISSUE TITLE
NullReferenceException in MixerInteractiveHelper

### ISSUE THREAD

**Issue by Mobius5150** [mixer/interactive-unity-plugin#94]
It seems that if you start a game and then leave it going for a while in the Unity editor you get flooded with NRE's in the MixerInteractiveHelper:

NullReferenceException: Object reference not set to an instance of an object
MixerInteractiveHelper.Update () (at Assets/MixerInteractive/Source/Scripts/MixerInteractiveHelper.cs:87)

![image](https://user-images.githubusercontent.com/1120274/42473465-8c98faf8-8379-11e8-9644-6d496289e866.png)

**Comment by mkpazon** [comment]
Any updates on this? I have the same problem.

**Comment by WatchaGames** [comment]
Hi, not yet encountered it but will probably will when doing longer demos, interested to see how is this solved.
