### ISSUE TITLE
exception after running several hours

### ISSUE THREAD

**Issue by payzer** [mixer/interactive-unity-plugin#96]
There are cases where there would be a stack like:

ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds | System.Array.Copy (System.Array sourceArray, Int32 sourceIndex, System.Array destinationArray, Int32 destinationIndex, Int32 length)
System.Array.Copy (System.Array sourceArray, System.Array destinationArray, Int32 length)
System.Collections.Generic.List`1[Microsoft.Mixer.InteractiveEventArgs].ToArray ()
Microsoft.Mixer.InteractivityManager.RaiseQueuedInteractiveEvents ()
Microsoft.Mixer.InteractivityManager.DoWork ()
MixerInteractive.DoWork ()
MixerInteractive.Update ()

or 

IndexOutOfRangeException: Array index is out of range. | System.Collections.Generic.Dictionary`2[System.UInt32,System.Collections.Generic.Dictionary`2[System.String,Microsoft.Mixer._InternalButtonState]].Do_CopyTo[UInt32,UInt32] (System.UInt32[] array, Int32 index, System.Collections.Generic.Transform`1 transform)
System.Collections.Generic.Dictionary`2+KeyCollection[System.UInt32,System.Collections.Generic.Dictionary`2[System.String,Microsoft.Mixer._InternalButtonState]].CopyTo (System.UInt32[] array, Int32 index)
System.Collections.Generic.List`1[System.UInt32].AddCollection (ICollection`1 collection)
System.Collections.Generic.List`1[System.UInt32]..ctor (IEnumerable`1 collection)
Microsoft.Mixer.InteractivityManager.ClearPreviousControlState ()
Microsoft.Mixer.InteractivityManager.DoWork ()
MixerInteractive.DoWork ()
MixerInteractive.Update ()

or 

NullReferenceException: Object reference not set to an instance of an object | Microsoft.Mixer.InteractivityManager.RaiseQueuedInteractiveEvents ()
Microsoft.Mixer.InteractivityManager.DoWork ()
MixerInteractive.DoWork ()
MixerInteractive.Update ()

**Comment by avi90** [comment]
We get these Exceptions too and I think they are threading related. For example here https://github.com/mixer/interactive-unity-plugin/blob/master/Source/InteractiveSDK/Assets/MixerInteractive/Source/Scripts/InteractivityManager.cs#L1268 the main unity thread accesses the `_queuedEvents` List, which can also be accessed by the Websocket-Thread unguarded.

**Comment by payzer** [comment]
Thank you. Yes, the root cause is what you said.
