### ISSUE TITLE
MixerInteractive.ClearSavedLoginInformation() requires exit of the application

### ISSUE THREAD

**Issue by payzer** [mixer/interactive-unity-plugin#97]
Calling MixerInteractive.ClearSavedLoginInformation() requires exiting the application. Ideally, you wouldn't have to.

(bug was reported from gitter)

**Comment by rasterknight** [comment]
Yes that would be nice. It would help greatly to start to have a boot-connect-play flow that can be assembled.
I'm a beginner at MixerUnity but setting up a flow of program start around the various functions available is quite unclear to me.
Thanks

**Comment by rasterknight** [comment]
Thanks for the pointers @payzer 
Working on my boot flow right now for my first proto of a game. Will post learnings.
